name: Build Docker Images

on: 
  push:
    branches:
      - master
      - test_action
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/**'
  pull_request:
    branches:
      - master
      - test_action
    paths:
      - 'src/**'
      - 'dockerfiles/**'
      - 'scripts/**'

jobs:
  test_build:
    runs-on: ubuntu-20.04
    name: Build GATK-SV Pipeline Docker Images
    env:
      PR_NUM: ${{ github.event.number }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      GITHUB_CONTEXT: ${{ toJson(github) }}
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install termcolor

      - name: Compile Args
        id: compose_image_tag
        run: |
          if [ github.event_name == 'pull_request' ]
          then
            x="AAAAA"
          else
            x="BBBBB"
          fi
          echo "::set-output name=action_fruit::${x}"

      - name: Run build_docker.py [Pull Request]
        if: github.event_name == 'pull_request'
        run: |
          cd ./scripts/docker/
          python build_docker.py --targets all --image-tag ${PR_NUM}-${COMMIT_SHA::8}

      - name: Run build_docker.py [Push]
        if: github.event_name == 'push'
        run: |
          echo "--------++---"
          MERGE_COMMIT_SHA=$(echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g')
          echo $MERGE_COMMIT_SHA
          TIME_STAMP=$(echo "$GITHUB_CONTEXT"| jq '.event.commits[].timestamp' | tail -2 | head -1 |sed 's/\"//g')
          DATE="$(cut -d'T' -f1 <<<${TIME_STAMP//-})"
          echo $TIME_STAMP
          echo $DATE
          echo "-------++----"
          echo ${{steps.compose_image_tag.outputs.action_fruit}}
          echo "-----------"
          echo ${GITHUB_CONTEXT}
          echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
          cd ./scripts/docker/
          python build_docker.py --targets all --image-tag ${PR_NUM}-${COMMIT_SHA::8}
